<?php require "templates/header.phtml" ?>
<div id="card-area">
    <div class="wrapper">
        <div class="box-area">
            <?php foreach($audiovisuales as $audiovisual) :?>
                <div class="box">
                    <img src="img/Audiovisuales/<?=$audiovisual->Artist_id?>.jpg" alt="Artista">
                    <div class="overlay">
                        <h3><?=$audiovisual->Artist_name?></h3>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem quisquam placeat
                            illo fugiat nulla! Consectetur?</p>
                        <a href="audiovisual/<?=$audiovisual->Artist_name?>">Conocelo más</a>
                    </div>
                </div>
            <?php endforeach ?>  
        </div>
    </div>
</div>
<?php require "templates/footer.phtml"?>
