<?php require "templates/header.phtml"?>
    <div id="card-area">
        <div class="wrapper">
            <div class="box-area">
                <?php foreach($artists as $artist) :?>
                    <div class="box">
                        <img src="img/Artistas/<?=$artist->Artist_id?>.jpg" alt="Artista">
                        <div class="overlay">
                            <h3><?=$artist->Artist_name?></h3>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem quisquam placeat
                                illo fugiat nulla! Consectetur?</p>
                            <a href="artista/<?=$artist->Artist_name?>">Conocelo más</a>
                        </div>
                    </div>
                <?php endforeach ?>  
            </div>
        </div>
    </div>
<?php require "templates/footer.phtml"?>