<?php require "templates/header.phtml" ?>

    <main class="main-content">
        <div class="container">
            <div class="card__container">
                <?php foreach($productores as $productor) :?>
                    <article class="card__article">
                        <img src="img/Productores/<?=$productor->Artist_id?>.jpg" alt="Card" class="card__img">

                        <div class="card__data">
                            <h3 class="card__title"> Artista <br> <?=$productor->Artist_name?></h3>
                        </div>

                        <img src="" alt="" class="card__bg">

                        <a href="Productor/<?=$productor->Artist_name?>" class="card__button">Conocelo más <i class="ri-arrow-right-line"></i></a>
                    </article>
                <?php endforeach ?>     
            </div>
        </div>
    </main>   

<?php require "templates/footer.phtml"?>