<?php require "templates/header.phtml"; ?>
<body>
    <section class="email-container">
        <input type="text" id="email" value="gacetaplay@gmail.com" readonly>
        <button id="copyButton">📋 Copiar</button>
        <button id="mailButton" ><a href="mailto:gacetaplay@gmail.com"></a>✉️</button>
    </section>

    <script src="script.js"></script>
</body>
<?php require "templates/footer.phtml"; ?>