    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col logofu">
                    <img class="logo-gaceta-footer" src="img/Logos/LOGO_BLANCO.png" alt="">
                </div>
                <div class="footer-col">
                    <h4>Navegá</h4>
                    <ul>
                        <li><a href="artistas">Artistas</a></li>
                        <li><a href="Productores">Productores</a></li>
                        <li><a href="Audiovisuales">Audiovisuales</a></li>
                        <li><a href="Contacto">Contacto</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Seguinos</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>