<footer>
    <div class="footer-container">
        <div class="footer-section logoFooterDiv">
            <a href="home"><img class="imgLogoFooter" src="img/Logos/LOGO_BLANCO.png" alt="Logo Gaceta Play"></a>
        </div>
        <div class="footer-section serviciosDiv">
            <h3>Servicios</h3>
            <a href="#">Productores</a>
            <a href="#">Audiovisuales</a>
            <a href="Contacto">Contactanos</a>
        </div>
    </div>
    <div class="footer-bottom">
        &copy; Gaceta Play. Todos los derechos reservados.
    </div>
</footer>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>