<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaceta Play</title>
    <link rel="stylesheet" href="css/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <header>
        <div class="logo">Gaceta Play</div href="home">
        <nav class="mainNavbar">
            <ul>
                <div class="dropdown" >
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" >
                        Artistas
                    </button>
                    <ul class="dropdown-menu">
                        //revisar 
                        <?php foreach ($artists as $artist) :
                            if ($artist->Category_id == 1) : ?>
                                <li ><a class="dropdown-item" href="artistas/<?= $artist->Artist_name ?>"></a><?php echo $artist->Artist_name ?></li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Productores
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Barta</a></li>
                        <li><a class="dropdown-item" href="#">Lonzo</a></li>
                        <li><a class="dropdown-item" href="#">Fosse</a></li>
                        <li><a class="dropdown-item" href="#">Tiano</a></li>
                        <li><a class="dropdown-item" href="#">Ara</a></li>
                        <li><a class="dropdown-item" href="#">Zekko</a></li>
                        <li><a class="dropdown-item" href="#">Tadu Vázquez</a></li> 
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Audiovisuales
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">antu.av</a></li>
                        <li><a class="dropdown-item" href="#">wocseall</a></li>
                        <li><a class="dropdown-item" href="#">madebysai</a></li>
                    </ul>
                </div>
            </ul>
        </nav>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
