<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <base href="'.BASE_URL.'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="icon" type="image/png" href="img/Logos/LOGO_NEGRO_1.png">
    <title>Gaceta Play</title>
    <link rel="stylesheet" href="css/styles.css">
</head>

<body >
    <header class="header">
        <div class="navLogo">
            <a href="home"><img src="img/Logos/LOGO_BLANCO.png" alt="" class="logo-img"></a>
            <a href="home">
                <h1 class="logo">gaceta <span class="playSpan">play</span></h1>
            </a>
        </div>

        <nav class="navbar">
            <a href="artistas">Artistas</a>
            <a href="Productores">Productores</a>
            <a href="Audiovisuales">Audiovisuales</a>
            <a href="#">Nosotros</a>
        </nav>
    </header>