<?php require "templates/header.phtml"; ?>
<div class="conteinerHome">
    <div class="contenedorTitulo">
        <h2 id="textoNovedades" data-text="novedades">novedades</h2>
    </div>
    <div class="contenedorCardsVideos">
        <button class="slider-button left">&#8249;</button>
        <div class="slider">
            <div class="cardList">
                <div class="cardVideo">
                    <div class="videoWrapper">
                        <iframe src="https://www.youtube.com/embed/SZtESyl2hns?si=Z8vl1MKyQWbQYGNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                    <p>escucha ramma</p>
                </div>
                <div class="cardVideo">
                    <div class="videoWrapper">
                        <iframe src="https://www.youtube.com/embed/SZtESyl2hns?si=Z8vl1MKyQWbQYGNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                    <p>escucha ramma</p>
                </div>
                <div class="cardVideo">
                    <div class="videoWrapper">
                        <iframe src="https://www.youtube.com/embed/SZtESyl2hns?si=Z8vl1MKyQWbQYGNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                    <p>escucha ramma</p>
                </div>
                <div class="cardVideo">
                    <div class="videoWrapper">
                        <iframe src="https://www.youtube.com/embed/SZtESyl2hns?si=Z8vl1MKyQWbQYGNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                    <p>escucha ramma</p>
                </div>
                <div class="cardVideo">
                    <div class="videoWrapper">
                        <iframe src="https://www.youtube.com/embed/SZtESyl2hns?si=Z8vl1MKyQWbQYGNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                    <p>escucha ramma</p>
                </div>
            </div>
        </div>
        <button class="slider-button right">&#8250;</button>
    </div>
</div>

    <script src="js/home.js"></script>

<?php require "templates/footer.phtml"; ?>
       



