<?php require "templates/headerSegundo.phtml" ?>
    <!-- <link rel="stylesheet" href="../css/styles.css"> REVISAR PUEDE Q ESTE BIEN, ME PARECE RARO -->
    <div class="mainSoloArtista">
        <div class="imagenesYbio" >
            <div class="divImagenes">
                <img src="" alt="Foto 1" class="imagen">
            </div>
            <div class="divisor"></div>
            <div class="bio">
                <h4> <?= $artistaName->Artist_tittle?> </h4>
                <div class="texto-bio">
                    <p><?= $artistaName->Artist_bio?> </p>
                </div>
            </div>
        </div>
        <!-- <div class="linksRedes">
            div pequeno con links a spotify/youtube instagram etc
        </div>
        <div class="novedades">
            div novedades
        </div> -->
    </div>
    
<?php require "templates/footerSegundo.phtml"?>