<?php require "templates/headerSegundo.phtml" ?>
    <div main>
        <div contenedor fotos y bio>
            <div>
                contenedor fotos de la izquierda
            </div>
            <div>
                div medio divisor
            </div>
            <div>
                div donde se encuentra la bio
            </div> 
        </div>
        <div>
            div pequeno con links a spotify/youtube instagram etc
        </div>
        <div>
            div novedades
        </div>
    </div>
    http://localhost/PROYECTO-GACETA/Productor/%E2%81%A0Fosse revisar
    si te paras en soloartista y queres ir a todos productores no podes
<?php require "templates/footer.phtml"?>