<?php require "templates/headerSegundo.phtml" ?>

    <div class="headerArtistas">
        <h1 id="nombreArtista"><?=$artistaName->Artist_name?></h1>
        <div class="redesArtista">
            <a href="#" id="instagram-link"><img src="../img/Logos/instagram3.png" alt="Instagram" class="redesLogo"></a>
            <a href="#" id="youtube-link"><img src="../img/Logos/Youtube3.png" alt="YouTube" class="redesLogo"></a>
            <a href="#" id="spotify-link"><img src="../img/Logos/spotify.png" alt="Spotify" class="redesLogo"></a>
        </div>
    </div>
    <div class="mainSoloArtista">
        <div class="imagenesYbio">
            <div class="divImagenes">
                <img src="../img/Artistas/<?=$artistaName->Artist_id?>.jpg" alt="Foto 1" class="imagen">
                <img src="../img/Artistas/<?=$artistaName->Artist_id?>.jpg" alt="Foto 2" class="imagen">

                <div class="redes">
                    <h4><?=$artistaName->Artist_name?></h4>
                </div>
            </div>
            <div class="bio">
                <h4><?= $artistaName->Artist_tittle?></h4>
                <div class="texto-bio">
                    <p><?= $artistaName->Artist_bio?></p>
                </div>
            </div>
        </div>
    </div>

    <!-- <script src="js/soloBios.js"></script> no funciona-->
    <!-- <div class="linksRedes">
        div pequeno con links a spotify/youtube instagram etc
    </div>
    <div class="novedades">
        div novedades
    </div> -->
    
<?php require "templates/footerSegundo.phtml"?>
