<?php require "templates/headerSegundo.phtml" ?>

    <div class="header-container">
        <div class="header-content">
            <h1><?=$artistaName->Artist_name?></h1>
            <div class="social-icons">
                <a href="#"><img src="../img/Logos/ig.png" alt="Instagram"></a>
                <a href="#"><img src="../img/Logos/spotify_icon.png" alt="Spotify"></a>
                <a href="#"><img src="../img/Logos/Youtube_Music_icon.png" alt="Youtube"></a>
                <a href="#"><img src="../img/Logos/tiktok.png" alt="TikTok"></a>
            </div>
            <div class="label-logo">
                <img src="../img/Logos/LOGO BLANCO-03.png" alt="Gaceta Play Logo">
            </div>
        </div>
    </div>

    <div class="container-platforms">
        <div class="album-cover">
            <img src="../img/Logos/intrepido.jpg" alt="Album Cover">
            <button class="play-button"><a href="https://open.spotify.com/intl-es/artist/7b0pdDyPV9f9hyDXAhk4Sg">▶</a></button>
        </div>
        <div class="platforms">
            <h3>Escuchá a <?=$artistaName->Artist_name?> en todas las plataformas</h2>
            <div class="platform-list">
                <div class="platform-item">
                    <img src="../img/Logos/spotify_icon.png" alt="Spotify">
                    <span>Spotify</span>
                </div>
                <div class="platform-item">
                    <img src="../img/Logos/Youtube_Music_icon.png" alt="YouTube Music">
                    <span>YouTube Music</span>
                </div>
                <div class="platform-item">
                    <img src="../img/Logos/amazon_music.png" alt="Amazon Music">
                    <span>Amazon Music</span>
                </div>
                <div class="platform-item">
                    <img src="../img/Logos/apple_music.png" alt="Apple Music">
                    <span>Apple Music</span>
                </div>
            </div>
        </div>
    </div> 

    

    <div class="mainSoloArtista">
        <div class="imagenesYbio">
            <div class="divImagenes">
                <img src="../img/Artistas/<?=$artistaName->Artist_id?>.jpg" alt="Foto 1" class="imagen">
                <img src="../img/Artistas/<?=$artistaName->Artist_id?>.jpg" alt="Foto 2" class="imagen">

                <div class="redes">
                    <h4><?=$artistaName->Artist_name?></h4>
                </div>
            </div>
            <div class="bio">
                <h4><?= $artistaName->Artist_tittle?></h4>
                <div class="texto-bio">
                    <p><?= $artistaName->Artist_bio?></p>
                </div>
            </div>
        </div>
    </div>

    <!-- <script src="js/soloBios.js"></script> no funciona-->
    <!-- <div class="linksRedes">
        div pequeno con links a spotify/youtube instagram etc
    </div>
    <div class="novedades">
        div novedades
    </div> -->
    
<?php require "templates/footerSegundo.phtml"?>
