<?php require "templates/headerSegundo.phtml" ?>
    <div main>
        <div contenedor fotos y bio>
            <div>
                contenedor fotos de la izquierda
            </div>
            <div>
                div medio divisor
            </div>
            <div>
                div donde se encuentra la bio
            </div>
        </div>
        <div>
            div pequeno con links a spotify/youtube sexoxox
        </div>
    </div>

    <?php require "templates/footer.phtml"?>